### ISSUE TITLE
Process the Splunk objects with ERB to allow for dynamic configuration

### ISSUE THREAD

**Issue by jfewins** [cerner/splunk-pickaxe#12]
I have a situation where the the Splunk index name used between two different environments is different (for example "my_index_dev" and "my_index_staging").  I would like to update this project to process the Splunk object files using ERB so that I can adjust the Splunk index referenced in the searches using an environment variable.

I have implemented this approach in my fork:
https://github.com/jfewins/splunk-pickaxe/commit/2fc0e481ef9294d0163394848203d026a3bf30d5

I'm also willing to consider alternative approaches.

**Comment by bbaugher** [comment]
This looks good. Would you want some way of defining environment variables in the environment config? https://github.com/cerner/splunk-pickaxe/blob/master/example-repo/.pickaxe.yml#L5

**Comment by jfewins** [comment]
Good idea.  I'll update the implementation to make all of the variables in the current environment available to the ERB processing.

**Comment by bbaugher** [comment]
Done by #13
