### ISSUE TITLE
Updating a report creates a new one with [Environment] name on it

### ISSUE THREAD

**Issue by abhishek321p** [cerner/splunk-pickaxe#21]
Updating a report creates a new one with [Environment] name on it.
example updating a report with name `MyTestSearch` in a `dev` environment creates a new one with the name `MyTestSearch [Dev]` and later updates the created new one for every other update.

**Comment by kaustubhgadre** [comment]
From the source code [1] and its comment, it looks like it was intended to work that way. 

I really want to use the same saved search in all the environments and utilize it in their dashboards xmls. Is there any specific reason around putting the environment in the name? If not, I know it will be a non-passive change, but can it fixed to NOT have the environment? 

[1] https://github.com/cerner/splunk-pickaxe/blob/master/lib/splunk/pickaxe/objects/reports.rb#L28

**Comment by bbaugher** [comment]
Yes I had originally done this because we always used our reports to email us about problems and this was an easy way to differentiate between the environments from the emails. We could look at adding a config option to disable this

**Comment by kaustubhgadre** [comment]
Thanks @bbaugher

**Comment by bbaugher** [comment]
Done by https://github.com/cerner/splunk-pickaxe/commit/07cc92085c716fa6f324a0669d59d2322c399a88

**Comment by abhishek321p** [comment]
@bbaugher that was really quick. thanks 👍 

Any estimate on when this will be available for us?

**Comment by bbaugher** [comment]
Would have been about now but I haven't published gems in awhile so having some troubles

**Comment by bbaugher** [comment]
Done, its available under 2.6.0
