### ISSUE TITLE
Support for "disabled" attribute in macros

### ISSUE THREAD

**Issue by kaustubhgadre** [cerner/splunk-pickaxe#27]
I currently use macros in splunk through the pickaxe tool. There is a "Disable" button in the Splunk UI which does not seem to be present in the pickaxe and its examples. 

If I understand the code correctly, it might be relatively simpler to add by adding a new key in here:
https://github.com/cerner/splunk-pickaxe/blob/master/lib/splunk/pickaxe/objects/supported_keys.rb#L8

Can we please have that support?

**Comment by bbaugher** [comment]
Sure feel free to open a PR, I don't really support this directly much anymore
