### ISSUE TITLE
Support Namespace config per environment

### ISSUE THREAD

**Issue by bbaugher** [cerner/splunk-pickaxe#8]
For consistency since we can now specify `emails` per environment we should support specifying `namespace` as well.

**Comment by regimus** [comment]
Since `app` is within `namespace`, I suppose I can expect this issue to also support specifying `app` on a per environment basis as well?

**Comment by bbaugher** [comment]
I guess we can, that feels inconsistent and odd but if for some reason the apps are named differently per environment but represent the same thing it makes sense

**Comment by bbaugher** [comment]
Sorry I totally forgot what namespace did, yes you would be able to provide app on a per environment basis

**Comment by bbaugher** [comment]
This was completed
